# Generated by Django 3.2.7 on 2023-03-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_thumbnail', models.ImageField(upload_to='photos/services')),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('services_description', models.TextField(max_length=500, unique=True)),
            ],
        ),
    ]
