# Generated by Django 3.2.7 on 2023-03-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_image', models.ImageField(upload_to='photos/vision')),
                ('our_vison', models.CharField(max_length=255, unique=True)),
                ('our_mission', models.CharField(max_length=255, unique=True)),
                ('green_title', models.CharField(max_length=255)),
                ('black_title', models.CharField(max_length=255)),
                ('ceo_word', models.TextField(max_length=500)),
                ('ceo_signature', models.ImageField(upload_to='photos/vision')),
                ('short_bio', models.TextField(max_length=5000)),
            ],
        ),
    ]
