# Generated by Django 3.2.7 on 2023-03-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_vision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vision',
            name='our_vison',
        ),
        migrations.AddField(
            model_name='vision',
            name='our_vision',
            field=models.TextField(default='hello', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vision',
            name='our_mission',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
