# Generated by Django 3.2.7 on 2023-03-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_vision', '0002_auto_20230313_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vision',
            name='short_bio',
        ),
        migrations.AddField(
            model_name='vision',
            name='short_bio_1',
            field=models.TextField(default='bef', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vision',
            name='short_bio_2',
            field=models.TextField(default='hello', max_length=300),
            preserve_default=False,
        ),
    ]
