version: "3.9"

services:
  elwedad:
    build:
      context: .
    restart: always
    volumes:
      - ./static:/elwedad/static
      - ./media:/elwedad/media
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
   
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  proxy:
    build:
      context: ..
    restart: always
    depends_on:
      - elwedad
    ports:
      - 80:8000
      - 443:443
    volumes:
      - ./static:/elwedad/static
      - ./media:/elwedad/media

volumes:
  postgres-data:
  static-data:

  static:
    driver: local
    driver_opts:
      type: none
      device: /elwedad/static
      o: bind