# Generated by Django 3.2.7 on 2023-08-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgrounds',
            old_name='section2_black',
            new_name='section2_black_add_the_first_bg_only',
        ),
        migrations.RemoveField(
            model_name='backgrounds',
            name='section2_green',
        ),
        migrations.AddField(
            model_name='backgrounds',
            name='section2_green_add_the_first_bg_only',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
