# Generated by Django 3.2.7 on 2023-08-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_auto_20230814_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section2_green', models.CharField(blank=True, max_length=255, null=True)),
                ('section2_black', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='backgrounds',
            name='section2_black_add_the_first_bg_only',
        ),
        migrations.RemoveField(
            model_name='backgrounds',
            name='section2_green_add_the_first_bg_only',
        ),
    ]
